name: flutter_memories_dailyjournal
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_secure_storage: any
  another_flushbar: any
  intl: ^0.18.1
  confirm_dialog: ^1.0.1
  flutter_quill: ^8.1.0
  dotted_border: ^2.0.0+3
  dropdown_button2: ^1.9.2
  image_picker: ^1.0.4
  path_provider: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^16.1.0
  easy_localization: ^3.0.1
  provider: any
  shared_preferences: any
  carousel_slider: ^4.2.1
  flutter_native_timezone: ^2.0.0
  easy_image_viewer: ^1.2.0
  restart_app: any
  google_sign_in: any
  table_calendar: ^3.0.8
  connectivity_plus: any
  fluttertoast: ^8.1.2
  flutter_html: ^3.0.0-alpha.6
  devicelocale: any
  share_plus: ^7.2.1
  screenshot: ^2.1.0
  gallery_saver: ^2.3.2
  zefyrka: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon_launcher/icon_launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icon_launcher/
    - assets/images/slider/
    - assets/translations/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Nunito
  #     fonts:
  #       - asset: assets/fonts/Nunito.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
